---
#
# Ansible managed
#
repository:
  description: Install and configure certbot on your system.
  homepage: https://robertdebock.nl/
  topics: certbot, acme, letsencrypt, security, ansible, molecule, tox, playbook
